services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-courses-api:practice5
    container_name: fastapi-courses-api
    ports:
      - "80:8000"
    restart: always
    init: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      COURSES_FILE: /app/courses.json
    stop_grace_period: 10s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
